customhost = "employee.c1enfd7clygp.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "cpac3009"
customdb = "employee"
custombucket = "lowchoonkeat-employee"
customregion = "us-east-1"
